name: Scene Builder Linux Bundles
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 14, 15 ]
    steps:
      - name: Install packages
        run: sudo apt-get install xdg-utils
      - uses: actions/checkout@v2
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - name: Create Bundle using JPackage
        run: |
          wget -P /tmp https://download2.gluonhq.com/openjfx/15.0.1/openjfx-15.0.1_linux-x64_bin-jmods.zip
          unzip /tmp/openjfx-15.0.1_linux-x64_bin-jmods.zip -d /tmp
          ./gradlew jlink jpackage
          sed -i "s/'deb'/'rpm'/g" app/build.gradle
          ./gradlew jpackage -PVERSION=${{ matrix.java }}
          ls app/build/
        env:
          JAVAFX_HOME: /tmp/javafx-jmods-15.0.1/
          JPACKAGE_HOME: ${{env.JAVA_HOME}}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SceneBuilder-${{ runner.os }}-${{ matrix.java }}
          path: |
            app/build/*.deb
            app/build/*.rpm