name: Scene Builder MacOS Bundles
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: 15
      - uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}
      - name: Create Bundle using JPackage
        run: |
          wget -P /tmp https://download2.gluonhq.com/openjfx/15.0.1/openjfx-15.0.1_osx-x64_bin-jmods.zip
          unzip /tmp/openjfx-15.0.1_osx-x64_bin-jmods.zip -d /tmp
          TAG=${GITHUB_REF/refs\/tags\//}
          ./gradlew jlink jpackage -PVERSION=$TAG
        env:
          JAVAFX_HOME: /tmp/javafx-jmods-15.0.1/
          JPACKAGE_HOME: ${{env.JAVA_HOME}}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SceneBuilder-${{ runner.os }}
          path: app/build/*.dmg
