name: Scene Builder Windows Bundles
on: [push]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 14, 15 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - name: Create Bundle using JPackage
        run: |
          echo ${{env.HOME}}
          bitsadmin /Transfer DownloadJavaFX https://download2.gluonhq.com/openjfx/15.0.1/openjfx-15.0.1_windows-x64_bin-jmods.zip ${{env.HOME}}\openjfx-15.0.1_windows-x64_bin-jmods.zip
          powershell -command "Expand-Archive -Force ${{env.HOME}}\openjfx-15.0.1_windows-x64_bin-jmods.zip ${{env.HOME}}"
          set JAVAFX_HOME=${{env.HOME}}\javafx-jmods-15.0.1
          set JPACKAGE_HOME=${{env.JAVA_HOME}}
          echo %JAVAFX_HOME%
          .\gradlew jpackage -PVERSION="12.0.0"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: app/build/*.dmg