name: Scene Builder Windows Bundles
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: 15
      - name: Create Bundle using JPackage
        run: |
          bitsadmin /Transfer DownloadJavaFX https://download2.gluonhq.com/openjfx/15.0.1/openjfx-15.0.1_windows-x64_bin-jmods.zip D:\openjfx-15.0.1_windows-x64_bin-jmods.zip
          powershell -command "Expand-Archive -Force D:\openjfx-15.0.1_windows-x64_bin-jmods.zip D:\"
          .\gradlew jlink jpackage
        env:
          JAVAFX_HOME: D:\javafx-jmods-15.0.1
          JPACKAGE_HOME: ${{env.JAVA_HOME}}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SceneBuilder-${{ runner.os }}
          path: app/build/*.msi